# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(resolve:ELASTICSEARCH_URL)%' }
    indexes:
        # "%indexe_elastic%appellation":*
        articles:
            properties:
                name: {type: text}
                content: {type: text}
            persistence:
                driver: orm
                model: App\Entity\Articles
        branches:
            properties:
                country: {type: text}
            persistence:
                driver: orm
                model: App\Entity\Branche
    # indexes:
    #     "%indexe_elastic%":
    #         client: { url: '%env(resolve:ELASTICSEARCH_URL)%' }
    #         types:
    #             rezocar:
    #                 mappings:
    #                     country: ~
    #                     place: ~
    #                 persistence:
    #                     driver: orm
    #                     model: App\Entity\Branche