# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(resolve:ELASTICSEARCH_URL)%' }
    indexes:
        # "%indexe_elastic%appellation":*
        branches:
            properties:
                country: {type: text}
            persistence:
                driver: orm
                model: App\Entity\Branche