<?php return array(
    'root' => array(
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => '51c2e1c428a45df8cd4329201728aea72d29e6de',
        'name' => '__root__',
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => '51c2e1c428a45df8cd4329201728aea72d29e6de',
            'dev_requirement' => false,
        ),
        'api-platform/core' => array(
            'pretty_version' => 'v2.7.11',
            'version' => '2.7.11.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../api-platform/core',
            'aliases' => array(),
            'reference' => '79f548640960c8df36d4048e2de3a7d7113fbd6b',
            'dev_requirement' => false,
        ),
        'composer/pcre' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/./pcre',
            'aliases' => array(),
            'reference' => '67a32d7d6f9f560b726ab25a061b38ff3a80c560',
            'dev_requirement' => true,
        ),
        'composer/semver' => array(
            'pretty_version' => '3.3.2',
            'version' => '3.3.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/./semver',
            'aliases' => array(),
            'reference' => '3953f23262f2bff1919fc82183ad9acb13ff62c9',
            'dev_requirement' => true,
        ),
        'composer/xdebug-handler' => array(
            'pretty_version' => '2.0.5',
            'version' => '2.0.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/./xdebug-handler',
            'aliases' => array(),
            'reference' => '9e36aeed4616366d2b690bdce11f71e9178c579a',
            'dev_requirement' => true,
        ),
        'doctrine/annotations' => array(
            'pretty_version' => '1.14.3',
            'version' => '1.14.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/annotations',
            'aliases' => array(),
            'reference' => 'fb0d71a7393298a7b232cbf4c8b1f73f3ec3d5af',
            'dev_requirement' => false,
        ),
        'doctrine/cache' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/cache',
            'aliases' => array(),
            'reference' => '1ca8f21980e770095a31456042471a57bc4c68fb',
            'dev_requirement' => false,
        ),
        'doctrine/collections' => array(
            'pretty_version' => '1.8.0',
            'version' => '1.8.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/collections',
            'aliases' => array(),
            'reference' => '2b44dd4cbca8b5744327de78bafef5945c7e7b5e',
            'dev_requirement' => false,
        ),
        'doctrine/common' => array(
            'pretty_version' => '3.4.3',
            'version' => '3.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/common',
            'aliases' => array(),
            'reference' => '8b5e5650391f851ed58910b3e3d48a71062eeced',
            'dev_requirement' => false,
        ),
        'doctrine/data-fixtures' => array(
            'pretty_version' => '1.6.6',
            'version' => '1.6.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/data-fixtures',
            'aliases' => array(),
            'reference' => '4af35dadbfcf4b00abb2a217c4c8c8800cf5fcf4',
            'dev_requirement' => true,
        ),
        'doctrine/dbal' => array(
            'pretty_version' => '3.6.2',
            'version' => '3.6.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/dbal',
            'aliases' => array(),
            'reference' => 'b4bd1cfbd2b916951696d82e57d054394d84864c',
            'dev_requirement' => false,
        ),
        'doctrine/deprecations' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/deprecations',
            'aliases' => array(),
            'reference' => '0e2a4f1f8cdfc7a92ec3b01c9334898c806b30de',
            'dev_requirement' => false,
        ),
        'doctrine/doctrine-bundle' => array(
            'pretty_version' => '2.7.2',
            'version' => '2.7.2.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../doctrine/doctrine-bundle',
            'aliases' => array(),
            'reference' => '22d53b2c5ad03929628fb4a928b01135585b7179',
            'dev_requirement' => false,
        ),
        'doctrine/doctrine-fixtures-bundle' => array(
            'pretty_version' => '3.4.4',
            'version' => '3.4.4.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../doctrine/doctrine-fixtures-bundle',
            'aliases' => array(),
            'reference' => '9ec3139c52a42e94c9fd1e95f8d2bca94326edfb',
            'dev_requirement' => true,
        ),
        'doctrine/doctrine-migrations-bundle' => array(
            'pretty_version' => '3.2.2',
            'version' => '3.2.2.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../doctrine/doctrine-migrations-bundle',
            'aliases' => array(),
            'reference' => '3393f411ba25ade21969c33f2053220044854d01',
            'dev_requirement' => false,
        ),
        'doctrine/event-manager' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/event-manager',
            'aliases' => array(),
            'reference' => '95aa4cb529f1e96576f3fda9f5705ada4056a520',
            'dev_requirement' => false,
        ),
        'doctrine/inflector' => array(
            'pretty_version' => '2.0.6',
            'version' => '2.0.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/inflector',
            'aliases' => array(),
            'reference' => 'd9d313a36c872fd6ee06d9a6cbcf713eaa40f024',
            'dev_requirement' => false,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '1.5.0',
            'version' => '1.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'reference' => '0a0fa9780f5d4e507415a065172d26a98d02047b',
            'dev_requirement' => false,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'reference' => '39ab8fcf5a51ce4b85ca97c7a7d033eb12831124',
            'dev_requirement' => false,
        ),
        'doctrine/migrations' => array(
            'pretty_version' => '3.5.5',
            'version' => '3.5.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/migrations',
            'aliases' => array(),
            'reference' => '4b1e2b6ba71d21d0c5be22ed03b6fc954d20b204',
            'dev_requirement' => false,
        ),
        'doctrine/orm' => array(
            'pretty_version' => '2.15.1',
            'version' => '2.15.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/orm',
            'aliases' => array(),
            'reference' => '9bc6f5b4ac6f1e7d4248b2efbd01a748782075bc',
            'dev_requirement' => false,
        ),
        'doctrine/persistence' => array(
            'pretty_version' => '3.1.4',
            'version' => '3.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/persistence',
            'aliases' => array(),
            'reference' => '8bf8ab15960787f1a49d405f6eb8c787b4841119',
            'dev_requirement' => false,
        ),
        'doctrine/sql-formatter' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/sql-formatter',
            'aliases' => array(),
            'reference' => '25a06c7bf4c6b8218f47928654252863ffc890a5',
            'dev_requirement' => false,
        ),
        'egulias/email-validator' => array(
            'pretty_version' => '3.2.5',
            'version' => '3.2.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../egulias/email-validator',
            'aliases' => array(),
            'reference' => 'b531a2311709443320c786feb4519cfaf94af796',
            'dev_requirement' => false,
        ),
        'elasticsearch/elasticsearch' => array(
            'pretty_version' => 'v7.17.2',
            'version' => '7.17.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../elasticsearch/elasticsearch',
            'aliases' => array(),
            'reference' => '2d302233f2bb0926812d82823bb820d405e130fc',
            'dev_requirement' => false,
        ),
        'ezimuel/guzzlestreams' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezimuel/guzzlestreams',
            'aliases' => array(),
            'reference' => 'b4b5a025dfee70d6cd34c780e07330eb93d5b997',
            'dev_requirement' => false,
        ),
        'ezimuel/ringphp' => array(
            'pretty_version' => '1.2.2',
            'version' => '1.2.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezimuel/ringphp',
            'aliases' => array(),
            'reference' => '7887fc8488013065f72f977dcb281994f5fde9f4',
            'dev_requirement' => false,
        ),
        'friendsofphp/php-cs-fixer' => array(
            'pretty_version' => 'v3.4.0',
            'version' => '3.4.0.0',
            'type' => 'application',
            'install_path' => __DIR__ . '/../friendsofphp/php-cs-fixer',
            'aliases' => array(),
            'reference' => '47177af1cfb9dab5d1cc4daf91b7179c2efe7fad',
            'dev_requirement' => true,
        ),
        'friendsofphp/proxy-manager-lts' => array(
            'pretty_version' => 'v1.0.14',
            'version' => '1.0.14.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../friendsofphp/proxy-manager-lts',
            'aliases' => array(),
            'reference' => 'a527c9d9d5348e012bd24482d83a5cd643bcbc9e',
            'dev_requirement' => false,
        ),
        'friendsofsymfony/elastica-bundle' => array(
            'pretty_version' => 'v6.2.0',
            'version' => '6.2.0.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../friendsofsymfony/elastica-bundle',
            'aliases' => array(),
            'reference' => '4a3e03f79ae6688056c54eb516b6dc263feb329f',
            'dev_requirement' => false,
        ),
        'fzaninotto/faker' => array(
            'pretty_version' => 'v1.9.2',
            'version' => '1.9.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fzaninotto/faker',
            'aliases' => array(),
            'reference' => '848d8125239d7dbf8ab25cb7f054f1a630e68c2e',
            'dev_requirement' => false,
        ),
        'guzzlehttp/ringphp' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.2.2',
            ),
        ),
        'laminas/laminas-code' => array(
            'pretty_version' => '4.7.1',
            'version' => '4.7.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-code',
            'aliases' => array(),
            'reference' => '91aabc066d5620428120800c0eafc0411e441a62',
            'dev_requirement' => false,
        ),
        'monolog/monolog' => array(
            'pretty_version' => '1.27.1',
            'version' => '1.27.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../monolog/monolog',
            'aliases' => array(),
            'reference' => '904713c5929655dc9b97288b69cfeedad610c9a1',
            'dev_requirement' => false,
        ),
        'nelmio/cors-bundle' => array(
            'pretty_version' => '2.3.1',
            'version' => '2.3.1.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../nelmio/cors-bundle',
            'aliases' => array(),
            'reference' => '185d2c0ae50a3f0b628790170164d5f1c5b7c281',
            'dev_requirement' => false,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v4.15.4',
            'version' => '4.15.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'reference' => '6bb5176bc4af8bcb7d926f88718db9b96a2d4290',
            'dev_requirement' => true,
        ),
        'nyholm/dsn' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nyholm/dsn',
            'aliases' => array(),
            'reference' => '9445621b426bac8c0ca161db8cd700da00a4e618',
            'dev_requirement' => false,
        ),
        'ocramius/proxy-manager' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '^2.1',
            ),
        ),
        'pagerfanta/core' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.8.0',
            ),
        ),
        'pagerfanta/doctrine-collections-adapter' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.8.0',
            ),
        ),
        'pagerfanta/doctrine-dbal-adapter' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.8.0',
            ),
        ),
        'pagerfanta/doctrine-mongodb-odm-adapter' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.8.0',
            ),
        ),
        'pagerfanta/doctrine-orm-adapter' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.8.0',
            ),
        ),
        'pagerfanta/doctrine-phpcr-odm-adapter' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.8.0',
            ),
        ),
        'pagerfanta/elastica-adapter' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.8.0',
            ),
        ),
        'pagerfanta/pagerfanta' => array(
            'pretty_version' => 'v3.8.0',
            'version' => '3.8.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pagerfanta/pagerfanta',
            'aliases' => array(),
            'reference' => 'a07c84296e491add39d103b812129de77610c33b',
            'dev_requirement' => false,
        ),
        'pagerfanta/solarium-adapter' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.8.0',
            ),
        ),
        'pagerfanta/twig' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.8.0',
            ),
        ),
        'paragonie/random_compat' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '2.*',
            ),
        ),
        'pdepend/pdepend' => array(
            'pretty_version' => '2.13.0',
            'version' => '2.13.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pdepend/pdepend',
            'aliases' => array(),
            'reference' => '31be7cd4f305f3f7b52af99c1cb13fc938d1cfad',
            'dev_requirement' => true,
        ),
        'php-cs-fixer/diff' => array(
            'pretty_version' => 'v2.0.2',
            'version' => '2.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-cs-fixer/diff',
            'aliases' => array(),
            'reference' => '29dc0d507e838c4580d018bd8b5cb412474f7ec3',
            'dev_requirement' => true,
        ),
        'phpdocumentor/reflection-common' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-common',
            'aliases' => array(),
            'reference' => '1d01c49d4ed62f25aa84a747ad35d5a16924662b',
            'dev_requirement' => false,
        ),
        'phpdocumentor/reflection-docblock' => array(
            'pretty_version' => '5.3.0',
            'version' => '5.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-docblock',
            'aliases' => array(),
            'reference' => '622548b623e81ca6d78b721c5e029f4ce664f170',
            'dev_requirement' => false,
        ),
        'phpdocumentor/type-resolver' => array(
            'pretty_version' => '1.7.1',
            'version' => '1.7.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/type-resolver',
            'aliases' => array(),
            'reference' => 'dfc078e8af9c99210337325ff5aa152872c98714',
            'dev_requirement' => false,
        ),
        'phpmd/phpmd' => array(
            'pretty_version' => '2.13.0',
            'version' => '2.13.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmd/phpmd',
            'aliases' => array(),
            'reference' => 'dad0228156856b3ad959992f9748514fa943f3e3',
            'dev_requirement' => true,
        ),
        'phpstan/phpdoc-parser' => array(
            'pretty_version' => '1.20.4',
            'version' => '1.20.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpstan/phpdoc-parser',
            'aliases' => array(),
            'reference' => '7d568c87a9df9c5f7e8b5f075fc469aa8cb0a4cd',
            'dev_requirement' => false,
        ),
        'psr/cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'reference' => 'd11b50ad223250cf17b86e38383413f5a6764bf8',
            'dev_requirement' => false,
        ),
        'psr/cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'psr/container' => array(
            'pretty_version' => '1.1.2',
            'version' => '1.1.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'reference' => '513e0666f7216c7459170d56df27dfcefe1689ea',
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/link' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/link',
            'aliases' => array(),
            'reference' => 'eea8e8662d5cd3ae4517c9b864493f59fca95562',
            'dev_requirement' => false,
        ),
        'psr/link-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0',
                1 => '1.0|2.0',
            ),
        ),
        'psr/simple-cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'react/promise' => array(
            'pretty_version' => 'v2.10.0',
            'version' => '2.10.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/promise',
            'aliases' => array(),
            'reference' => 'f913fb8cceba1e6644b7b90c4bfb678ed8a3ef38',
            'dev_requirement' => false,
        ),
        'ruflin/elastica' => array(
            'pretty_version' => '7.3.1',
            'version' => '7.3.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ruflin/elastica',
            'aliases' => array(),
            'reference' => '7c61a630c3d456b00a5610960ae3a9bd29987469',
            'dev_requirement' => false,
        ),
        'sensio/framework-extra-bundle' => array(
            'pretty_version' => 'v5.6.1',
            'version' => '5.6.1.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../sensio/framework-extra-bundle',
            'aliases' => array(),
            'reference' => '430d14c01836b77c28092883d195a43ce413ee32',
            'dev_requirement' => false,
        ),
        'squizlabs/php_codesniffer' => array(
            'pretty_version' => '3.7.2',
            'version' => '3.7.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../squizlabs/php_codesniffer',
            'aliases' => array(),
            'reference' => 'ed8e00df0a83aa96acf703f8c2979ff33341f879',
            'dev_requirement' => true,
        ),
        'swiftmailer/swiftmailer' => array(
            'pretty_version' => 'v6.3.0',
            'version' => '6.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../swiftmailer/swiftmailer',
            'aliases' => array(),
            'reference' => '8a5d5072dca8f48460fce2f4131fcc495eec654c',
            'dev_requirement' => false,
        ),
        'symfony/asset' => array(
            'pretty_version' => 'v4.4.46',
            'version' => '4.4.46.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/asset',
            'aliases' => array(),
            'reference' => '6ef0f9f352f90c469e8b363ebc038d81a7198873',
            'dev_requirement' => false,
        ),
        'symfony/cache' => array(
            'pretty_version' => 'v4.4.48',
            'version' => '4.4.48.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/cache',
            'aliases' => array(),
            'reference' => '3b98ed664887ad197b8ede3da2432787212eb915',
            'dev_requirement' => false,
        ),
        'symfony/cache-contracts' => array(
            'pretty_version' => 'v2.5.2',
            'version' => '2.5.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/cache-contracts',
            'aliases' => array(),
            'reference' => '64be4a7acb83b6f2bf6de9a02cee6dad41277ebc',
            'dev_requirement' => false,
        ),
        'symfony/cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'symfony/config' => array(
            'pretty_version' => 'v4.4.44',
            'version' => '4.4.44.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/config',
            'aliases' => array(),
            'reference' => 'ed42f8f9da528d2c6cae36fe1f380b0c1d8f0658',
            'dev_requirement' => false,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v4.4.49',
            'version' => '4.4.49.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'reference' => '33fa45ffc81fdcc1ca368d4946da859c8cdb58d9',
            'dev_requirement' => false,
        ),
        'symfony/debug' => array(
            'pretty_version' => 'v4.4.44',
            'version' => '4.4.44.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/debug',
            'aliases' => array(),
            'reference' => '1a692492190773c5310bc7877cb590c04c2f05be',
            'dev_requirement' => false,
        ),
        'symfony/debug-bundle' => array(
            'pretty_version' => 'v4.4.37',
            'version' => '4.4.37.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/debug-bundle',
            'aliases' => array(),
            'reference' => 'f21cce588be146c9111cb9041f0784a6534fd648',
            'dev_requirement' => false,
        ),
        'symfony/dependency-injection' => array(
            'pretty_version' => 'v4.4.49',
            'version' => '4.4.49.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dependency-injection',
            'aliases' => array(),
            'reference' => '9065fe97dbd38a897e95ea254eb5ddfe1310f734',
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.5.2',
            'version' => '2.5.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'reference' => 'e8b495ea28c1d97b5e0c121748d6f9b53d075c66',
            'dev_requirement' => false,
        ),
        'symfony/doctrine-bridge' => array(
            'pretty_version' => 'v4.4.48',
            'version' => '4.4.48.0',
            'type' => 'symfony-bridge',
            'install_path' => __DIR__ . '/../symfony/doctrine-bridge',
            'aliases' => array(),
            'reference' => '8dbbec53714eb512321380d582b45ff7e074a5d6',
            'dev_requirement' => false,
        ),
        'symfony/dotenv' => array(
            'pretty_version' => 'v4.4.37',
            'version' => '4.4.37.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dotenv',
            'aliases' => array(),
            'reference' => 'fcedd6d382b3afc3e1e786aa4e4fc4cf06f564cf',
            'dev_requirement' => false,
        ),
        'symfony/error-handler' => array(
            'pretty_version' => 'v4.4.44',
            'version' => '4.4.44.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/error-handler',
            'aliases' => array(),
            'reference' => 'be731658121ef2d8be88f3a1ec938148a9237291',
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => 'v4.4.44',
            'version' => '4.4.44.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'reference' => '1e866e9e5c1b22168e0ce5f0b467f19bba61266a',
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-contracts' => array(
            'pretty_version' => 'v1.1.13',
            'version' => '1.1.13.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher-contracts',
            'aliases' => array(),
            'reference' => '1d5cd762abaa6b2a4169d3e77610193a7157129e',
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.1',
            ),
        ),
        'symfony/expression-language' => array(
            'pretty_version' => 'v4.4.47',
            'version' => '4.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/expression-language',
            'aliases' => array(),
            'reference' => 'e4964c7636e19f6008660f450c09121c80c2a7b9',
            'dev_requirement' => false,
        ),
        'symfony/filesystem' => array(
            'pretty_version' => 'v4.4.42',
            'version' => '4.4.42.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/filesystem',
            'aliases' => array(),
            'reference' => '815412ee8971209bd4c1eecd5f4f481eacd44bf5',
            'dev_requirement' => false,
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v4.4.44',
            'version' => '4.4.44.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'reference' => '66bd787edb5e42ff59d3523f623895af05043e4f',
            'dev_requirement' => false,
        ),
        'symfony/flex' => array(
            'pretty_version' => 'v1.19.5',
            'version' => '1.19.5.0',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../symfony/flex',
            'aliases' => array(),
            'reference' => '51077ed0f6dc2c94cd0b670167eee3747c31b2c1',
            'dev_requirement' => false,
        ),
        'symfony/form' => array(
            'pretty_version' => 'v4.4.48',
            'version' => '4.4.48.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/form',
            'aliases' => array(),
            'reference' => 'e1d137b13e0ec2cb5c5e38debca7a510c6f858c6',
            'dev_requirement' => false,
        ),
        'symfony/framework-bundle' => array(
            'pretty_version' => 'v4.4.49',
            'version' => '4.4.49.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/framework-bundle',
            'aliases' => array(),
            'reference' => 'd8cf2558249004a29b8e27b1f6eae52337ff471b',
            'dev_requirement' => false,
        ),
        'symfony/http-client-contracts' => array(
            'pretty_version' => 'v2.5.2',
            'version' => '2.5.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-client-contracts',
            'aliases' => array(),
            'reference' => 'ba6a9f0e8f3edd190520ee3b9a958596b6ca2e70',
            'dev_requirement' => false,
        ),
        'symfony/http-foundation' => array(
            'pretty_version' => 'v4.4.49',
            'version' => '4.4.49.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-foundation',
            'aliases' => array(),
            'reference' => '191413c7b832c015bb38eae963f2e57498c3c173',
            'dev_requirement' => false,
        ),
        'symfony/http-kernel' => array(
            'pretty_version' => 'v4.4.50',
            'version' => '4.4.50.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-kernel',
            'aliases' => array(),
            'reference' => 'aa6df6c045f034aa13ac752fc234bb300b9488ef',
            'dev_requirement' => false,
        ),
        'symfony/inflector' => array(
            'pretty_version' => 'v4.4.44',
            'version' => '4.4.44.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/inflector',
            'aliases' => array(),
            'reference' => '66185be61805b1e44a5c4000929e700228d426cc',
            'dev_requirement' => false,
        ),
        'symfony/intl' => array(
            'pretty_version' => 'v4.4.47',
            'version' => '4.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/intl',
            'aliases' => array(),
            'reference' => 'f1d0f9d91ab482d33423b788999fbb43c34a9a59',
            'dev_requirement' => false,
        ),
        'symfony/maker-bundle' => array(
            'pretty_version' => 'v1.39.1',
            'version' => '1.39.1.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/maker-bundle',
            'aliases' => array(),
            'reference' => '30c8ac13511f6df7bc9ac088f31d7a48ce6433c6',
            'dev_requirement' => true,
        ),
        'symfony/mime' => array(
            'pretty_version' => 'v4.4.47',
            'version' => '4.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/mime',
            'aliases' => array(),
            'reference' => '0eaf33cd6d1b3eaa50e7bc48b17f6e45789df35d',
            'dev_requirement' => false,
        ),
        'symfony/monolog-bridge' => array(
            'pretty_version' => 'v4.4.43',
            'version' => '4.4.43.0',
            'type' => 'symfony-bridge',
            'install_path' => __DIR__ . '/../symfony/monolog-bridge',
            'aliases' => array(),
            'reference' => 'ad09c9980b912e757c4ecd8363cebf3039d1d471',
            'dev_requirement' => false,
        ),
        'symfony/monolog-bundle' => array(
            'pretty_version' => 'v3.8.0',
            'version' => '3.8.0.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/monolog-bundle',
            'aliases' => array(),
            'reference' => 'a41bbcdc1105603b6d73a7d9a43a3788f8e0fb7d',
            'dev_requirement' => false,
        ),
        'symfony/options-resolver' => array(
            'pretty_version' => 'v4.4.44',
            'version' => '4.4.44.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/options-resolver',
            'aliases' => array(),
            'reference' => '583f56160f716dd435f1cd721fd14b548f4bb510',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-iconv' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-intl-icu' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-icu',
            'aliases' => array(),
            'reference' => 'a3d9148e2c363588e05abbdd4ee4f971f0a5330c',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'reference' => '639084e360537a19f9ee352433b84ce831f3d2da',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'reference' => '19bd1e4fcd5b91116f14d8533c57831ed00571b6',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'reference' => '8ad114f6b39e2c98a8b0e3bd907732c207c2b534',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php56' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php70' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php71' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php72',
            'aliases' => array(),
            'reference' => '869329b1e9894268a8a61dabb69153029b7a8c97',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php73' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php73',
            'aliases' => array(),
            'reference' => '9e8ecb5f92152187c4799efd3c96b78ccab18ff9',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'reference' => '7a6ff3f1959bb01aefccb463a0f2cd3d3d2fd936',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php81' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php81',
            'aliases' => array(),
            'reference' => '707403074c8ea6e2edaf8794b0157a0bfa52157a',
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v4.4.44',
            'version' => '4.4.44.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'reference' => '5cee9cdc4f7805e2699d9fd66991a0e6df8252a2',
            'dev_requirement' => false,
        ),
        'symfony/property-access' => array(
            'pretty_version' => 'v4.4.44',
            'version' => '4.4.44.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/property-access',
            'aliases' => array(),
            'reference' => 'd49682f6f0764df725c95128213a38f7e0a9f358',
            'dev_requirement' => false,
        ),
        'symfony/property-info' => array(
            'pretty_version' => 'v4.4.49',
            'version' => '4.4.49.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/property-info',
            'aliases' => array(),
            'reference' => '971cf46634e44d93d2174cf004555b69b19c9487',
            'dev_requirement' => false,
        ),
        'symfony/routing' => array(
            'pretty_version' => 'v4.4.44',
            'version' => '4.4.44.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/routing',
            'aliases' => array(),
            'reference' => 'f7751fd8b60a07f3f349947a309b5bdfce22d6ae',
            'dev_requirement' => false,
        ),
        'symfony/security-bundle' => array(
            'pretty_version' => 'v4.4.50',
            'version' => '4.4.50.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/security-bundle',
            'aliases' => array(),
            'reference' => '076fd2088ada33d760758d98ff07ddedbf567946',
            'dev_requirement' => false,
        ),
        'symfony/security-core' => array(
            'pretty_version' => 'v4.4.48',
            'version' => '4.4.48.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/security-core',
            'aliases' => array(),
            'reference' => '423ccb332784b236dfe6c5f396d0ac49db57c914',
            'dev_requirement' => false,
        ),
        'symfony/security-csrf' => array(
            'pretty_version' => 'v4.4.37',
            'version' => '4.4.37.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/security-csrf',
            'aliases' => array(),
            'reference' => '45c956ef58135091f53732646a0acd28034f02c0',
            'dev_requirement' => false,
        ),
        'symfony/security-guard' => array(
            'pretty_version' => 'v4.4.46',
            'version' => '4.4.46.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/security-guard',
            'aliases' => array(),
            'reference' => 'f199eb1b19db11ce254b891580728c45a7ccacfd',
            'dev_requirement' => false,
        ),
        'symfony/security-http' => array(
            'pretty_version' => 'v4.4.50',
            'version' => '4.4.50.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/security-http',
            'aliases' => array(),
            'reference' => '7fa4a0cac16f02cb534a6e9adcdb17385f94004f',
            'dev_requirement' => false,
        ),
        'symfony/serializer' => array(
            'pretty_version' => 'v4.4.47',
            'version' => '4.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/serializer',
            'aliases' => array(),
            'reference' => '6e01d63c55657930a6de03d6e36aae50af98888d',
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v2.5.2',
            'version' => '2.5.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'reference' => '4b426aac47d6427cc1a1d0f7e2ac724627f5966c',
            'dev_requirement' => false,
        ),
        'symfony/service-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'symfony/stopwatch' => array(
            'pretty_version' => 'v4.4.46',
            'version' => '4.4.46.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/stopwatch',
            'aliases' => array(),
            'reference' => '757660703fbd139eea0001b759c6c3bf5bc3ea52',
            'dev_requirement' => false,
        ),
        'symfony/swiftmailer-bundle' => array(
            'pretty_version' => 'v3.5.4',
            'version' => '3.5.4.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/swiftmailer-bundle',
            'aliases' => array(),
            'reference' => '9daab339f226ac958192bf89836cb3378cc0e652',
            'dev_requirement' => false,
        ),
        'symfony/templating' => array(
            'pretty_version' => 'v4.4.44',
            'version' => '4.4.44.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/templating',
            'aliases' => array(),
            'reference' => '2bfe94a5ebe0176612186e5f6b6a08a480c9e1f9',
            'dev_requirement' => false,
        ),
        'symfony/translation-contracts' => array(
            'pretty_version' => 'v2.5.2',
            'version' => '2.5.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation-contracts',
            'aliases' => array(),
            'reference' => '136b19dd05cdf0709db6537d058bcab6dd6e2dbe',
            'dev_requirement' => false,
        ),
        'symfony/twig-bridge' => array(
            'pretty_version' => 'v4.4.49',
            'version' => '4.4.49.0',
            'type' => 'symfony-bridge',
            'install_path' => __DIR__ . '/../symfony/twig-bridge',
            'aliases' => array(),
            'reference' => 'd6b0fbfd5e2fab79c0c7b8dfe579e47ee0999113',
            'dev_requirement' => false,
        ),
        'symfony/twig-bundle' => array(
            'pretty_version' => 'v4.4.41',
            'version' => '4.4.41.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/twig-bundle',
            'aliases' => array(),
            'reference' => '164c1edc69f2c7ee337323efc78a8a8a263f45ff',
            'dev_requirement' => false,
        ),
        'symfony/validator' => array(
            'pretty_version' => 'v4.4.48',
            'version' => '4.4.48.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/validator',
            'aliases' => array(),
            'reference' => '54781a4c41efbd283b779110bf8ae7f263737775',
            'dev_requirement' => false,
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => 'v4.4.47',
            'version' => '4.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'reference' => '1069c7a3fca74578022fab6f81643248d02f8e63',
            'dev_requirement' => false,
        ),
        'symfony/var-exporter' => array(
            'pretty_version' => 'v5.4.21',
            'version' => '5.4.21.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-exporter',
            'aliases' => array(),
            'reference' => 'be74908a6942fdd331554b3cec27ff41b45ccad4',
            'dev_requirement' => false,
        ),
        'symfony/web-link' => array(
            'pretty_version' => 'v4.4.37',
            'version' => '4.4.37.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/web-link',
            'aliases' => array(),
            'reference' => 'ab13621fd0c0119ad9ebc7179be7c5a1fc6a542d',
            'dev_requirement' => false,
        ),
        'symfony/web-profiler-bundle' => array(
            'pretty_version' => 'v4.4.47',
            'version' => '4.4.47.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/web-profiler-bundle',
            'aliases' => array(),
            'reference' => 'c173202d8ce82fde63ec0953eaffdf065018b8f4',
            'dev_requirement' => false,
        ),
        'symfony/web-server-bundle' => array(
            'pretty_version' => 'v4.4.44',
            'version' => '4.4.44.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/web-server-bundle',
            'aliases' => array(),
            'reference' => 'b58e4ab115c6f6879f6e0de35c08b2dfd9e24c3b',
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v4.4.45',
            'version' => '4.4.45.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'reference' => 'aeccc4dc52a9e634f1d1eebeb21eacfdcff1053d',
            'dev_requirement' => false,
        ),
        'twig/extensions' => array(
            'pretty_version' => 'v1.5.4',
            'version' => '1.5.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twig/extensions',
            'aliases' => array(),
            'reference' => '57873c8b0c1be51caa47df2cdb824490beb16202',
            'dev_requirement' => false,
        ),
        'twig/twig' => array(
            'pretty_version' => 'v2.15.5',
            'version' => '2.15.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twig/twig',
            'aliases' => array(),
            'reference' => 'fc02a6af3eeb97c4bf5650debc76c2eda85ac22e',
            'dev_requirement' => false,
        ),
        'webmozart/assert' => array(
            'pretty_version' => '1.11.0',
            'version' => '1.11.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webmozart/assert',
            'aliases' => array(),
            'reference' => '11cb2199493b2f8a3b53e7f19068fc6aac760991',
            'dev_requirement' => false,
        ),
        'willdurand/negotiation' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../willdurand/negotiation',
            'aliases' => array(),
            'reference' => '68e9ea0553ef6e2ee8db5c1d98829f111e623ec2',
            'dev_requirement' => false,
        ),
    ),
);
