FROM php:7.4-apache


# install apache avec php 7.4
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

# install pdo_pgql intl
RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions pdo_pgsql intl

# install composer 
RUN curl -sS https://getcomposer.org/installer | php --  --disable-tls && \
    mv composer.phar /usr/local/bin/composer
# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# installer node si besoin
RUN apt update && apt install -yqq nodejs npm

COPY . /var/www/

# changer var/www/html en symfony var/www/public
COPY ./docker/apache.conf /etc/apache2/sites-available/000-default.conf

ENV PATH="/composer/vendor/bin:$PATH" \
    COMPOSER_ALLOW_SUPERUSER=1

RUN cd /var/www && \
    composer install --no-plugins --no-scripts && \
    composer update --no-plugins --no-scripts --ignore-platform-req=ext-gd
    # composer update --lock && \
    # composer config allow-plugins.acme/plugin true &&\
    # composer install --no-scripts --no-interaction && \
    # npm install && \
    # npm run build


# changer le /html en /www
WORKDIR /var/www/

EXPOSE 80